repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: venv/bin/python -m ruff check .
        language: system
        pass_filenames: false
        types_or: [python, pyi]

      - id: pytest
        name: pytest
        entry: venv/bin/python -m pytest
        language: system
        pass_filenames: false
        always_run: true

      - id: build
        name: build package
        entry: venv/bin/python -m build
        language: system
        pass_filenames: false
        always_run: true
